name: gwak
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy
  - astropy
  # frame file I/O dependencies
  - python-ldas-tools-framecpp
  - python-nds2-client
  # omicron dependencies
  - python-ligo-lw
  - pyomicron
  - omicron>=4.0.0
  - dqsegdb2
  - uproot
  # injection dependencies
  - bilby<1.2
  - lalsuite
  - pip:
    - tensorflow==2.12.0
    - scipy==1.6.1
    - scikit-learn
    - h5py
    - snakemake
    - matplotlib
    - numpy
    - setGPU
    - pre-commit
